---
title: "HW 7: BSTA 511/611 F25"
pagetitle: "HW 7"
author: "Your name here - update this!!!!"
date: "Due Sat 12/6/25"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    number-sections: false
    number-depth: 4
    theme: lumen
    embed-resources: true
    html-math-method: mathjax
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE, fig.height = 2, fig.width = 4)
```

**Due Sat 12/6/25**

Download the .qmd file for this assignment from <https://github.com/niederhausen/BSTA_511_F25/blob/main/homework/HW_7_F25_bsta511.qmd>

## Graded exercises

The exercises listed below will be graded for this assignment. You are **strongly** encouraged to complete the entire assignment. You will receive feedback on exercises you turn in that are not being graded.

-   **Book exercises**
    -   6.28, 6.32
-   **R exercises**
    -   R1: Life expectancy vs. CO2 emissions parts (a)-(j)
-   **Nonparametric exercises**
    -   NPT 1, NPT 2, NPT 3

## Directions

::: callout-important
-   Complete ALL exercises in this assignment using Quarto.
-   **Use LaTeX to format equations.** 
    -   See the .qmd files from class notes for LaTeX code to make it easier to show your work in computations.
    -   For instructions on creating equations in the Visual editor, check out <https://quarto.org/docs/get-started/authoring/rstudio.html#equations>. [html](../slides_code/Probability_distributions_in_R_bsta511.qmd)
    -   Also check out examples of [LaTeX formatting for statistics](https://nwakim.github.io/S2024_BSTA_513/extra_resources/Latex_qmd_formatting.html) created by recent biostats alum Ariel Weingarten.
    -   If you have difficulty rendering the LaTeX equations, I recommend installing and running the R package `tinytex`. See this [website](https://evalsp20.classes.andrewheiss.com/reference/install/#install-tinytex-1) for instructions.
:::

**Hypothesis test instructions**

::: callout-important
-   For book exercises, make sure to include all steps in a hypothesis test (where applicable) as outlined in the class notes.

-   Do not forget to include a discussion on whether you think the test (or CI) assumptions have been satisfied. Are there assumptions you need to make in order for them to be satisfied? Whether you believe they are satisfied or not, continue to run the hypothesis test (or CI) as instructed.
:::

-   Please upload your homework to [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F25/tool/094ccc0a-8f85-4069-af5b-e035ef8b79e2). **Upload both your .qmd code file and the rendered .html file** (or just your pdf if completing the assignment by hand).
    -   Use the assignment .qmd file linked to above as a template for your own assignment.
-   Please always use the following naming convention for submitting your files:
    -   **Lastname_Firstname_HWx.qmd**, such as Niederhausen_Meike_HW2.qmd
    -   **Lastname_Firstname_HWx.html**, such as Niederhausen_Meike_HW2.html
-   For each question, make sure to **show all of your work**.
    -   This includes all code and resulting output in the html file to support your answers for exercises requiring work done in R (including any arithmetic calculations).
    -   For non-calculation questions, this includes an explanation of your answer (*why did you choose your answer?*).
-   For each question, include a **sentence summarizing the answer** for that question in the context of the research question.

::: callout-tip
It is a good idea to try rendering your document from time to time as you go along! Note that rendering automatically saves your Qmd file and rendering frequently helps you catch your errors more quickly.
:::

# Book exercises




## 6.26 (a, e) Helmets and lunches 

[__Skip parts (b)-(d). To complete (e), use that the slope from part (b) is −0.537, and the intercept is 55.34.__]{style="color:purple"}

[_Note: if you have time, it would be good practice to calculate the regression line as well. This was covered on the previous assignment._]{style="color:purple"} 




## 6.28 Guppies, Part V 




## 6.32 (a, b) Guppies, Part VI  

__Skip part (c).__






# R exercises

## Load packages

Load all the packages you need in the first code chunk of the file that starts with `#| label: "setup"`.


## R1: Life expectancy vs. CO2 emissions 

Use the dataset [`Gapminder_2011_LifeExp_CO2.csv`](https://github.com/niederhausen/BSTA_511_F25/blob/main/data/Gapminder_2011_LifeExp_CO2.csv)

Data were downloaded from https://www.gapminder.org/data/.  

* __Life expectancy__ = the average number of years a newborn child would live if current mortality patterns were to stay the same. Source: https://www.gminder.org/data/documentation/gd004/

* __CO2 emissions (tons per person)__ = Carbon dioxide emissions from the burning of fossil fuels (metric tons of CO2 per person). Source: https://cdiac.ess-dive.lbl.gov/

* 2011 is the most recent year with the most complete data

### (a) Load data

__Load the dataset `Gapminder_2011_LifeExp_CO2.csv` and do a quick inspection of it. What are the dimensions? Variable names?__




### (b) Linear association?

__Make a scatterplot of life expectancy vs. CO2 emissions per person showing the best fit line and describe the relationship between the variables. In addition comment on whether the relationship looks linear or not.__




### (c) SLR

__Run the simple linear regression of life expectancy vs.CO2 emissions per person, and write out the corresponding regression equation. __




### (d) Prediction

__Using the regression equation, what is the expected life expectancy for a country with $CO_2$ emissions 20 metric tons per person?__




### (e) Independent data points?

__Explain whether you think the data point are independent of each other or not.__




### (f) Normality of residuals?

__Make a histogram, density plot, and boxplot of the model's residuals. What is the distribution shape of the residuals? What shape do we want them to have?__




### (g) QQ plot

__Make a QQ plot of the model's residuals.Explain whether or not the distribution of the residuals deviates from normality and how you made that conclusion based on the QQ plot.__




### (h) Random Normal QQ plots

__Make 5 QQ plots with points randomly generated from a normal distribution, where the number of points matches the sample size used in the linear model.__




### (i) QQ plot comparison

__Compare the QQ plot of the model's residuals to the randomly generated QQ plots. Is the QQ plot of the residuals similar to the randomly generated plots or different? Based on the these QQ plots, do you think it's possible that the residuals could be normally distributed?__




### (j) Equality of variance of the residuals?

__Make a residual plot. Describe what the plot looks like and whether there are any patterns in the residuals, and whether the equality of variance assumption the residuals seems to be satisfied or not.__




### (k) Transformation: log(x)

__Add a new variable to the dataset for the natural logarithm (`log()`) of the CO2 emissions per person values.__




### (l) Linear association (with transformation)?

__Make a scatterplot of life expectancy vs. log of CO2 emissions per person showing the best fit line and describe the relationship between the variables. In addition comment on whether the relationship looks linear or not.__




### (m) SLR (with transformation)

__Run the simple linear regression of life expectancy vs.CO2 emissions per person, and write out the corresponding regression equation.__




### (n) Prediction (with transformation)

__Using the regression equation, what is the expected life expectancy for a country with $CO_2$ emissions 20 metric tons per person?__




### (o) Compare predictions from without and with transformation

__Compare the predicted values from the models with and without the transformation. Which is bigger and why? Explain in terms of visually comparing the respective regression lines on the scatterplots.__




### (p) Normality of residuals (with transformation)?

__Make a histogram, density plot, and boxplot of the model's residuals. What is the distribution shape of the residuals? What shape do we want them to have?__




### (q) QQ plot (with transformation)

__Make a QQ plot of the model's residuals.Explain whether or not the distribution of the residuals deviates from normality and how you made that conclusion based on the QQ plot.__




### (r) Random Normal QQ plots (with transformation)

__Compare the QQ plot of the model's residuals to the randomly generated QQ plots (use the ones you generated above). Is the QQ plot of the residuals similar to the randomly generated plots or different? Based on the these QQ plots, do you think it's possible that the residuals could be normally distributed?__




### (s) Equality of variance of the residuals (with transformation)?

__Make a residual plot. Describe what the plot looks like and whether there are any patterns in the residuals, and whether the equality of variance assumption the residuals seems to be satisfied or not.__




### (t) Comparison of models without and with transformation

__Which of the models do you think has a better fit? Make sure your explanation comments on each of the LINE assumptions, and also compare the $R^2$ values from the models.__







# Nonparametric Tests


## NPT 1: Sign test

__Vegetarian diet and cholesterol levels__

When covering paired t-tests on Day 10 Part 2, the class notes used the example of testing whether a vegetarian diet changed cholesterol levels. The data are in the file `chol213.csv` at <https://niederhausen.github.io/BSTA_511_F24/data/chol213.csv>. In this exercise we will use non-parametric tests to test for a change and compare the results to the paired t-test.


### (a) Hypotheses

__What are the hypotheses for the sign test (2-sided) in the context of the problem?__ 





### (b) $D^+$ and $D^-$

__Calculate $D^+$ and $D^-$, the number of positive and negative differences when the differences are calculated as `After - Before`.__ 



### (c) Probability distribution

__What probability distribution can be used to model the number of positive differences? Make sure to specify its parameters.__ 




### (d) Exact probability

__Find the exact probability that there were at most 3 positive differences.__ 




### (e) Sign test in R

__Run the sign test in R. What is the sign test p-value and how does it compare to the p-value of the paired t-test (check the class notes for this)? __ 




### (f) S

__The sign test output includes the value for `S`. What is `S` and what does it measure?__ 




### (g) p-value

__Does the probability that there were at most 3 positive differences match the p-value from the R output? Why or why not?__ 




### (h) Normal approximation

__Would it be appropriate to use a normal approximation to calculate the p-value for this test? Why or why not?__ 



## NPT 2: (Wilcoxon) Signed-rank test

__Vegetarian diet and cholesterol levels__

When covering paired t-tests on Day 10 Part 2, the class notes used the example of testing whether a vegetarian diet changed cholesterol levels. The data are in the file `chol213.csv` at <https://niederhausen.github.io/BSTA_511_F23/data/chol213.csv>. In this exercise we will use non-parametric tests to test for a change and compare the results to the paired t-test.


### (a) Hypotheses

__What are the hypotheses for the (Wilcoxon) Signed-rank test (2-sided) in the context of the problem?__ 


### (b) Signed ranks

__Find the signed ranks. Make sure to account for ties when doing so.__ 

*Hint: See the extra code from the code file to help with this: <https://niederhausen.github.io/BSTA_511_F24/slides_code/Day17_bsta511_code.html#new-calculate-rankss-using-rank>.*


### (c) $T^+$

__Calculate the sum of the positive ranks ( $T^+$ ) __ 




### (d) Exact p-value

__Can an exact p-value for the (Wilcoxon) Signed-rank test be calculated? Why or why not?__ 




### (e) ormal approximation

__Is it appropriate to use the normal approximation method in this case?__ 




### (f) Test in R

__Run the (Wilcoxon) Signed-rank test in R. What is the  p-value and how does it compare to the p-value of the sign test and the paired t-test (check the class notes for this)?__ 




### (g) Condition

__There's one more condition that should be satisfied  to use the (Wilcoxon) Signed-rank test that has not been asked about yet in these questions. What is it and do you think it's satisfied?__ 






## NPT 3: Wilcoxon rank-sum test

__Does caffeine increase finger taps/min?__

When covering 2-sample t-tests on Day 11, the class notes used the example of testing whether caffeine increases finger taps/min. The data are in the file `CaffeineTaps.csv` at <https://niederhausen.github.io/BSTA_511_F23/data/CaffeineTaps.csv>. In this exercise we will use a non-parametric test and compare the results to the paired t-test.


### (a) Condition

__What condition needs to be satisfied to apply the Wilcoxon rank-sum test and is it satisfied for these data?__ 




[__Answer the following questions using the Wilcoxon rank-sum test whether you think the condition has been satisfied or not.__ ]{style="color:green"}

### (b) Why Wilcoxon rank-sum test?

__How would we know to use the Wilcoxon rank-sum test instead of the sign test or (Wilcoxon) Signed-rank test?__ 




### (c) Hypotheses

__What are the hypotheses for the Wilcoxon rank-sum test (1-sided) in the context of the problem? __ 



### (d) Exact test in R

__Run the exact Wilcoxon rank-sum test in R. What warning(s) does it give you?__ 




### (e) Normal approximation test in R

__Run the Wilcoxon rank-sum test in R with the normal approximation. Comment on whether it is appropriate to use the normal approximation or not in this case.__ 




### (f) p-value

__What is the p-value and how does it compare to the p-value of the 2-sample t-test (check the class notes for this)?__ 



### (g) Conclusion

__Write a conclusion to the test in the context of the problem.__ 









