---
title: "Week 7"
description: "Inference for difference in means, one proportion, and difference in proportions, and power"
pagetitle: "Week 7 BSTA 511/611"
date: "11/10/2025"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---



## Overview of Week 7

::::: grid
::: g-col-6
### Mon: Day 11

-   Inference for difference in means from two independent sample (2-sample t-test)
-   Power and sample size calculations
:::

::: g-col-6
### Wed: Day 12

-   Inference for proportions
    -   CIs vs. hypothesis tests
    -   One proportion from one sample
    -   Difference in proportions from two independent samples
:::
:::::

## Slides & Recordings

-   **Pre-recorded** lessons are on [Echo Video](https://echo360.org/section/af47457c-bed2-48d7-84ae-eaa2d44f9add/home).

| Day | Topic | Slides: html | Slides: pdf | Slides: web-page | Slides with notes | Recording Link | Duration | Code: qmd | Code: html |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| 11 | 2-sample means test: 5.3.2 | [Day 11: slides 1-17](../slides/Day11_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day11_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day11_bsta511_md.qmd) | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day11_bsta511_2samp-t-test-notes.pdf) | [Day 11 Part 1](https://echo360.org/lesson/049eaaed-5724-4d46-a36f-604aa498da61/classroom) | 36 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F25/blob/main/slides_code/Day11_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day11_bsta511_code.qmd) |
|  | 2-sample means CI; R; pooled SD: 5.3.1, 5.3.5 | [Day 11: slides 18-26](../slides/Day11_bsta511.qmd#/step-5-conclusion-to-hypothesis-test) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day11_bsta511_md.qmd#step-5-conclusion-to-hypothesis-test) | same | [Day 11 Part 2](https://echo360.org/lesson/d073fd64-ef7c-42e4-a03b-f0012cfb420f/classroom) | 26 min | same | same |
|  | Power & sample size: 1 or 2 means: 5.4 & extra | [Day 11: slides 27-45](../slides/Day11_bsta511.qmd#/power-and-sample-size-calculations) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day11_bsta511_md.qmd#power-and-sample-size-calculations) | same | [Day 11 Part 3](https://echo360.org/lesson/517a229a-1dd7-4645-a748-c328c64a5e36/classroom) | 57 min | same | same |
| 12 | 1 & 2 proportions test & CI: 8.1.1, 8.2 | [Day 12: slides 1-23](../slides/Day12_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day12_bsta511.pdf) \* | [{{< iconify streamline web size=20px >}}](../slides_md/Day12_bsta511_md.qmd) | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day12_bsta511_notes.pdf) \* | [Day 12 Part 1](https://echo360.org/lesson/87f67b21-1aa5-48f2-a8a4-cad10c42d4a5/classroom) | 48 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F25/blob/main/slides_code/Day12_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day12_bsta511_code.qmd) |
|  | R: 1 & 2 proportions test & CI | [Day 12: slides 24-34](../slides/Day12_bsta511.qmd#/r-1--and-2-sample-proportions-tests) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day12_bsta511_md.qmd#r-1--and-2-sample-proportions-tests) | same | [Day 12 Part 2](https://echo360.org/lesson/227afa33-fbff-4554-b84a-c280a2977b2d/classroom) | 26 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day12_bsta511_code.qmd#and-2-sample-proportions-tests-in-r) |
|  | Power for 1- and 2- proportions | [Day 12: slides 35-43](../slides/Day12_bsta511.qmd#/power-sample-size-for-testing-proportions) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day12_bsta511_md.qmd#power-sample-size-for-testing-proportions) | same | [Day 12 Part 3](https://echo360.org/lesson/25f9fd05-496c-4f30-92e8-8681d894ef2b/classroom) | 25 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day12_bsta511_code.qmd#power-sample-size-for-testing-proportions) |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5, 6, 6, 5, 5\]"}

`*`*Note: page numbers in pdf files do not always align with those in the original html slides*

## Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F25/tree/main/data)

-   Day 11: [CaffeineTaps.csv](/data/CaffeineTaps.csv)

## Practice Problems

### [Day 11 PP]{style="color:darkorange"}

-   Book exercises: 5.34, 4.22  

### [Day 12 PP]{style="color:darkorange"}

-   Book exercise: 8.2

## Class discussion

During class you will be working in groups discussing the following:

### Day 11

-   Practice Problems listed above
-   Book 5.26 a-b
-   R2: DDS expenditures by ethnicity (parts A-L)
-   PSS1: Book 4.24 - Power & sample size T/F questions
-   PSS2: Power & sample size calculations

### Day 12

Coming soon!

-   Practice Problems listed above
-   Book
    -   8.8 (see instructions in HW),
    -   8.24 (see instructions in HW)

## Homework

-   [HW 4](../homework/HW_4_F25_bsta511.qmd) covers Days 10-12 and is due on Sat, 11/15
-   Check out this [spreadsheet](https://docs.google.com/spreadsheets/d/1k_NivXZftdlRgRyTT3fUZCndW4eoXCzAs-DEIml6K3Y/edit?gid=0#gid=0) for typos in book.
