---
title: "Week 10"
description: "Simple Linear Regression (cont'd) and Nonparametric Tests"
pagetitle: "Week 10 BSTA 511/611"
date: "12/1/2025"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Overview of Week 10

-   [Exams 2 & 3 corrections information](#sec-ExamCorrections) is below.

::::: grid
::: g-col-6
### Mon: Day 16

-   Simple Linear Regression Part 2
-   Sections 6.3-6.4
:::

::: g-col-6
### Wed: Day 17

-   Nonparametric tests
-   This material is not in our textbook. Please see Chapter 13: Nonparametric tests of Pagano’s *Principles of Biostatistics*, 2022 edition as a supplementary resource.
    -   This chapter can be downloaded from the OHSU library’s eBook at <https://ebookcentral.proquest.com/lib/ohsu/detail.action?docID=6950388&pq-origsite=primo>
:::
:::::

## Slides & Recordings

-   **Pre-recorded** lessons are on [Echo Video](https://echo360.org/section/af47457c-bed2-48d7-84ae-eaa2d44f9add/home).

| Day | Topic | Slides: html | Slides: pdf | Slides: web-page | Slides with notes | Recording Link | Duration | Code: qmd | Code: html |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| 16 | Simple Linear Regression cont'd: 6.3-6.4 | [Day 16](../slides/Day16_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day16_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day16_bsta511_md.qmd) |  | [Day 16](https://echo360.org/lesson/2dc60cec-bd00-4eae-abb3-ba70d9cd6923/classroom) [\*]{style="color:darkorange"} | 1 hr 26 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F25/blob/main/slides_code/Day16_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day16_bsta511_code.qmd) |
| 17 | Sign test & Sign-rank test: Slides 1-31 |  | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day17_bsta511.pdf) |  | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day17_bsta511_notes.pdf) | [Day 17 Part 1](https://echo360.org/lesson/5c806486-fec8-45c8-9857-042abcba1f14/classroom) | 56 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F25/blob/main/slides_code/Day17_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day17_bsta511_code.qmd) |
|  | Wilcoxon rank-sum test, Kruskal-Wallis test: Slides 32-53 |  | same |  | same | [Day 17 Part 2](https://echo360.org/lesson/38c21b3d-88af-4a63-8c4b-5aeb7d19207b/classroom) | 41 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day17_bsta511_code.qmd#wilcoxon-rank-sum-test-1) |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5, 6, 6, 5, 5\]"}

[*`*`Edited live recording from F23 class*]{style="color:darkorange"}

## Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F25/tree/main/data)

-   Day 16: [lifeexp_femlit_water_2011.csv](/data/lifeexp_femlit_water_2011.csv)
-   HW 7: [Gapminder_2011_LifeExp_CO2.csv](/data/Gapminder_2011_LifeExp_CO2.csv)

## Practice Problems

### [Day 16 PP]{style="color:darkorange"}

-   Book exercises: 6.12, 6.20


### [Day 17 PP]{style="color:darkorange"}

-   None. Start working on the homework questions. 

## Class discussion

During class you will be working in groups discussing the following:

### Day 16

-   Questions from HW 7
    -   Book
        -   6.28, 6.32
    -   R1 (a) - (j): Life expectancy vs. CO~2~ emissions
    

### Day 17

-   Questions from HW 7
    -   Nonparametric Tests: NPT 1-3

## Homework

-   [HW 7](../homework/HW_7_F25_bsta511.qmd) covers Days 16 -17 and is due on Sat, 12/6
    -   Dataset for question R1: [Gapminder_2011_LifeExp_CO2.csv](/data/Gapminder_2011_LifeExp_CO2.csv)
-   Check out this [spreadsheet](https://docs.google.com/spreadsheets/d/1k_NivXZftdlRgRyTT3fUZCndW4eoXCzAs-DEIml6K3Y/edit?gid=0#gid=0) for typos in book.

## Exam Corrections {#sec-ExamCorrections}

-   Please *email* me a link to your video by the due date.
    -   *Please do not attach the video to the email*.
-   Exam corrections will be video recordings of you explaining what the error was on the problem, why it was incorrect, and the correct solution.
    -   Recordings do not need to include video of yourself.
-   I strongly recommend reviewing the class notes and homework solutions for examples of the level of detail and correct notation to use in your work.
-   You may not ask anyone for help (including AI) other than the instructor for doing your exam corrections.

### Exam 2 Corrections {#sec-Exam2Corrections}

-   Due on **Thursday 12/4** at 11 pm.
-   You are allowed exam corrections for two questions.
-   For **question 3**, you can earn back **all** of the points missed.
-   For **questions 1, 2, and 4**, you can earn back up to **half** of the missed points.
    -   For example, if on question 2 you scored 5 out of 10 points, you can increase your score up to 7.5 out of 10 points

### Exam 3 Corrections {#sec-Exam3Corrections}

-   Due **Monday 12/8** at 11 pm
-   You may do corrections for all questions.
-   For 10 parts to questions, you can earn back all of the points missed.
    -   For example, maybe you decide to choose parts 1b, 1c, 1d, 2c, 3a, 3d, 3f, 4b, 4d, and 4f as the 10 "parts of questions" that you want to be considered for getting full points back for.
    -   *When emailing me a link to your video, please clearly state which parts of questions you chose as the 10 to get full points back.*
-   For the remaining parts to questions, you can earn back up to half of the missed points.
