---
title: "Week 4"
description: "Random variables; Binomial, Normal & Poisson distributions"
pagetitle: "Week 4 BSTA 511/611"
date: "10/19/2026"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## [Page not yet updated]{style="color:darkorange"}

## Overview of Week 4

::::: grid
::: g-col-6
### Mon: Day 6

-   Random variables: Section 3.1
-   Binomial distribution: Section 3.2
-   [**Day 6 Practice Problems**]{style="color:darkorange"}
    -   See PP section below
            
:::

::: g-col-6
### Wed: Day 7

-   Normal distribution: Section 3.3
-   Poisson distribution: Section 3.4
-   [**Day 7 Practice Problems**]{style="color:darkorange"}
    -   See PP section below
:::
:::::

-   See the [Exam 1 information](#sec-Exam1info) section below for information about next week's exam.

## Slides & Recordings

-   **Pre-recorded** lessons are on [Echo Video](https://echo360.org/section/af47457c-bed2-48d7-84ae-eaa2d44f9add/home).

| Day | Topic | Slides: html | Slides: pdf | Slides: web-page | Slides with notes | Recording Link | Duration | Code: qmd | Code: html |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
|  | Calculating probabilities in R |  |  |  |  |  |  | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F26/blob/main/slides_code/Probability_distributions_in_R_bsta511.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Probability_distributions_in_R_bsta511.qmd) |
| []{.day-divider} |  |  |  |  |  |  |  |  |  |
| 6 | Random Variables (3.1.1-3.1.3) | [Day 6: slides 1-6](../slides/Day06_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../LaTeX_slides/Day06_bsta511.pdf) |  | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day06_bsta511_notes.pdf) | [Day 6 Part 1](https://echo360.org/lesson/219f3510-459e-4e87-8bf4-70361caf15d9/classroom) | 24 min |  |  |
|  | Linear combinations of RV's (3.1.4) | [Day 6: slides 7-10](../slides/Day06_bsta511.qmd) |  |  |  | [Day 6 Part 2](https://echo360.org/lesson/fecace43-fd5f-40b0-80aa-bea13937a25d/classroom) | 14 min |  |  |
|  | Binomial dist (3.2) | [Day 6: slides 11-15](../slides/Day06_bsta511.qmd) |  |  |  | [Day 6 Part 3](https://echo360.org/lesson/14424f6c-5256-4f72-b310-1d8015e8e6f7/classroom) | 27 min |  |  |
| []{.day-divider} |  |  |  |  |  |  |  |  |  |
| 7 | Normal dist and prob's for standard normal (3.3.1, 3.3.3) | [Day 7: slides 1-5](../slides/Day07_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../LaTeX_slides/Day07_bsta511.pdf) |  | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day07_bsta511_notes.pdf) | [Day 7 Part 1](https://echo360.org/lesson/1572e2ac-9780-4875-a143-daaf48d206d6/classroom) | 27 min |  |  |
|  | Normal prob's using z-scores (3.3.2, 3.3.4) | [Day 7: slides 6-7](../slides/Day07_bsta511.qmd) |  |  |  | [Day 7 Part 2](https://echo360.org/lesson/c825e1a4-b2ae-4a64-a27d-02ba1a1844ee/classroom) | 15 min |  |  |
|  | Normal approx of binomial dist (3.3.6) | [Day 7: slides 8-9](../slides/Day07_bsta511.qmd) |  |  |  | [Day 7 Part 3](https://echo360.org/lesson/476e16cc-5f56-41d2-a245-974d1aa78e67/classroom) | 14 min |  |  |
|  | Poisson dist (3.4) | [Day 7: slides 10-12](../slides/Day07_bsta511.qmd) |  |  |  | [Day 7 Part 4](https://echo360.org/lesson/8be6a464-56dc-437a-930e-fb0d0a7f3a1d/classroom) | 15 min |  |  |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5, 6, 6, 5, 5\]"}


## Practice Problems

### [Day 6 PP]{style="color:darkorange"}

-   From Day 6 slides: 
    -   **Example 3.11** on pg 6 of slides
    -   **Example 3.17 *parts (1) - (3)*** on pg 10 of slides
        -   *Hint: If you are unsure how to define the random variable T, take a look at how we defined the random variable M in example 3.16 for the amount of money one gets from 3 rolls of a die.*
    -   **Example 3.22** parts (1) and (2) on pg 14 of slides

### [Day 7 PP]{style="color:darkorange"}

-   From Day 7 slides: 
    -   **Example 3.3 parts (1) and (3)** on pg 7 of slides
    -   **Example 3.8 parts (2) and (3)** on pg 11 of slides

## Class discussion

During class you will be working in groups discussing the following:

### Day06

-   Practice Problems listed above
-   *Part (4)* of Example 3.17 on pg 10 of slides 
-   From HW 3
    -   Book exercises
        -   3.4, 3.8
    -   Non-book exercise
        -   NB 1
-   If you want some R practice, try the following:
    -   Example 3.3 on pg 2 of slides
        -   Write R code to calculate the expected value by defining vectors in R with the relevant values and then doing the appropriate calculations with the vectors.
        -   Hint: start with `x <- 1:6`.
    -   Example 3.10 on pg 5 of slides
        -   Write R code to calculate the variance and standard deviation by defining vectors in R with the relevant values and then doing the appropriate calculations with the vectors.

### Day 7

-   Practice Problems listed above
-   From HW 3:
    -   Book exercises
        -   3.22, 3.32, 3.40


## Homework

-   [HW 3](../homework/HW_3_F26_bsta511_v2.qmd) covers Days 6-7 and is due on Sat, 10/24
-   Make sure to check out the calculating probabilities in R code file: [qmd](https://github.com/niederhausen/BSTA_511_F26/blob/main/slides_code/Probability_distributions_in_R_bsta511.qmd), [html](../slides_code/Probability_distributions_in_R_bsta511.qmd)
-   Note: the answer to exercise 3.31(b) in the textbook (not assigned) is incorrect.
    -   Check out this [spreadsheet](https://docs.google.com/spreadsheets/d/1k_NivXZftdlRgRyTT3fUZCndW4eoXCzAs-DEIml6K3Y/edit?gid=0#gid=0) for more typos in book.

## Exam 1 information {#sec-Exam1info}

-   Exam 1 will be on Wed, Oct. 28th
-   *Chapters 1-2:* samples of [past exam questions](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F25/Exam_samples/Exam_1_samples_Ch1-2.pdf) and [answers](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F25/Exam_samples/Exam_1_samples_Ch1-2%20answers.pdf) (on Brightspace)
-   *Sections 3.1-3.4:* samples of [past exam questions](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F25/Exam_samples/Exam_2_samples_Ch3.1-3.4_4.1-4.2.pdf) and [answers](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F25/Exam_samples/Exam_2_samples_Ch3.1-3.4_4.1-4.2_answers.pdf) (on Brightspace)
    -   *Questions on Sections 4.1-4.2 in this file are not on Exam 1.*
-   Material will cover **Days 1-7**,
    -   which is approximately **Chapters 1, 2, and Sections 3.1-3.4** from the textbook.
-   The exam will be in-class and handwritten. *Bring a calculator.*
-   You may bring one page of notes on an 8.5” x 11” sheet of paper.
    -   You may use both sides.
    -   You may type your notes.
    -   You may **not** use screenshots of the notes or textbook
    -   You will be turning in the page of notes with the exam, so please add your name to the sheet.
