---
title: "Week 5"
description: "Normal & Poisson distributions; Variability in estimates & CI's"
pagetitle: "Week 5 BSTA 511/611"
date: "10/27/2025"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Overview of Week 5

::::: grid
::: g-col-6
### Mon: Day 7

-   Normal distribution: Section 3.3
-   Poisson distribution: Section 3.4

:::

::: g-col-6
### Wed: Days 8 & 9

-   **Day 8** topics: Variability in estimates: Section 4.1
-   **Day 9** topics:
    -   Confidence intervals for one mean (single-sample):
        -   Sections 4.2 and 5.1.1, 5.1.2 (pgs. 238-242)
    -   Student’s t-distribution
:::
:::::

-   [**Days 7-9 Practice Problems**]{style="color:darkorange"}
    -   See new PP section below


## Slides & Recordings

-   **Pre-recorded** lessons are on [Echo Video](https://echo360.org/section/af47457c-bed2-48d7-84ae-eaa2d44f9add/home).

| Day | Topic | Slides: html | Slides: pdf | Slides: web-page | Slides with notes | Recording Link | Duration | Code: qmd | Code: html |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
|  | Calculating probabilities in R |  |  |  |  |  |  | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F25/blob/main/slides_code/Probability_distributions_in_R_bsta511.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Probability_distributions_in_R_bsta511.qmd) |
| 7 | Normal dist and prob's for standard normal (3.3.1, 3.3.3) | [Day 7: slides 1-5](../slides/Day07_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../LaTeX_slides/Day07_bsta511.pdf) |  | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day07_bsta511_notes.pdf) | [Day 7 Part 1](https://echo360.org/lesson/1572e2ac-9780-4875-a143-daaf48d206d6/classroom) | 27 min |  |  |
| 7 | Normal prob's using z-scores (3.3.2, 3.3.4) | [Day 7: slides 6-7](../slides/Day07_bsta511.qmd) | same |  | same | [Day 7 Part 2](https://echo360.org/lesson/c825e1a4-b2ae-4a64-a27d-02ba1a1844ee/classroom) | 15 min |  |  |
| 7 | Normal approx of binomial dist (3.3.6) | [Day 7: slides 8-9](../slides/Day07_bsta511.qmd) | same |  | same | [Day 7 Part 3](https://echo360.org/lesson/476e16cc-5f56-41d2-a245-974d1aa78e67/classroom) | 14 min |  |  |
| 7 | Poisson dist (3.4) | [Day 7: slides 10-12](../slides/Day07_bsta511.qmd) | same |  | same | [Day 7 Part 4](https://echo360.org/lesson/8be6a464-56dc-437a-930e-fb0d0a7f3a1d/classroom) | 15 min |  |  |
| 8 | Variability in estimates: Section 4.1 | [Day 8: slides 1-13](../slides/Day08_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day08_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day08_bsta511_md.qmd) | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day08_bsta511_notes.pdf) | [Day 8 Part 1](https://echo360.org/lesson/bb8878be-5646-411c-bfdf-7bf246d44c8b/classroom) | 26 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F25/blob/main/slides_code/Day08_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day08_bsta511_code.qmd) |
| 8 | 4.1 con'td | [Day 8: slides 14-29](../slides/Day08_bsta511.qmd#/random-samples-of-size-n-5-from-yrbss2) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day08_bsta511_md.qmd#random-samples-of-size-n-5-from-yrbss2) | same | [Day 8 Part 2](https://echo360.org/lesson/348d5653-1289-4430-9772-5201e572a6f4/classroom) | 37 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day08_bsta511_code.qmd#random-samples-of-size-n-5-from-yrbss2) |
| 8 | R code demo |  |  |  |  | [Day 8 Part 3](https://echo360.org/lesson/449985e9-3d5c-41c7-9934-5a75c51367b3/classroom) | 11 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day08_bsta511_code.qmd) |
| 9 | CI's for 1 mean: 4.2 | [Day 9: slides 1-12](../slides/Day09_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day09_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day09_bsta511_md.qmd) | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day09_bsta511_notes.pdf) | [Day 9 Part 1](https://echo360.org/lesson/12a76ee1-6ecd-415f-b0c8-c4fa40d9b687/classroom) | 17 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F24/blob/main/slides_code/Day09_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day09_bsta511_code.qmd) |
| 9 | 4.2 con'td | [Day 9: slides 13-19](../slides/Day09_bsta511.qmd#/how-to-interpret-a-c-i-12) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day09_bsta511_md.qmd#how-to-interpret-a-c-i-12) | same | [Day 9 Part 2](https://echo360.org/lesson/f591aa8b-b8ad-479e-91f0-d170b53b66f8/classroom) | 17 min | same | same |
| 9 | 4.2 con'td, 5.1.1, 5.1.2 (pgs. 238-242) | [Day 9: slides 20-23](../slides/Day09_bsta511.qmd#/calculating-the-c-i-for-the-population-mean-using-s) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day09_bsta511_md.qmd#calculating-the-c-i-for-the-population-mean-using-s) | same | [Day 9 Part 3](https://echo360.org/lesson/7940464f-f788-4438-bc28-0859225d57fa/classroom) | 14 min | same | same |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5, 6, 6, 5, 5\]"}

## Practice Problems

### [Day 7 PP]{style="color:darkorange"}

-   From Day 7 slides: 
    -   **Example 3.3 parts (1) and (3)** on pg 7 of slides
    -   **Example 3.8 parts (2) and (3)** on pg 11 of slides

### [Day 8 & 9 PP]{style="color:darkorange"}

-   From Day 8 slides: 
    -   Slide 21: match figures to distribution (Sampling high schoolers’ weights)
    -   Book exercise: 4.2
-   From Day 9 slides: 
    -   Slide 15: What percent CI was being simulated in this figure?
    -   Slide 22: Calculate CI   


## Class discussion

During class you will be working in groups discussing the following:

### Day 7

-   Practice Problems listed above
-   From (updated) HW 3:
    -   Book exercises
        -   3.22, 3.32, 3.40

### Day 8 & 9

-   Practice Problems listed above
-   From  (updated) HW 3:
    -   Day 8
        -   R1: Youth weights Part 1 (YRBSS)
        -   Non-book exercise: Ethan Allen
    -   Day 9
        -   Book exercises:
            -   warm-up: 4.4, 4.6, 5.10
            -   5.6
        -   R2: Youth weights Part 2 (YRBSS)


## Homework

-   [HW 3 v2](../homework/HW_3_F25_bsta511_v2.qmd) covers Days 6 - 9 and is due on Sat, 11/1
-   Make sure to check out the calculating probabilities in R code file: [qmd](https://github.com/niederhausen/BSTA_511_F25/blob/main/slides_code/Probability_distributions_in_R_bsta511.qmd), [html](../slides_code/Probability_distributions_in_R_bsta511.qmd)
-   Note: the answer to exercise 3.31(b) in the textbook (not assigned) is incorrect.
    -   Check out this [spreadsheet](https://docs.google.com/spreadsheets/d/1k_NivXZftdlRgRyTT3fUZCndW4eoXCzAs-DEIml6K3Y/edit?gid=0#gid=0) for more typos in book.


## Exam 2 information {#sec-Exam2info}

-   Exam 2 will be on Wed, Nov. 5th
-   Samples of [past exam questions](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F25/Exam_samples/Exam_2_samples_Ch3.1-3.4_4.1-4.2.pdf) and [answers](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F25/Exam_samples/Exam_2_samples_Ch3.1-3.4_4.1-4.2_answers.pdf) (on Sakai)
-   Material will cover **Days 6-9**,
    -   which is approximately **Sections 3.1-3.4, 4.1-4.2** from the textbook.
-   The exam will be in-class and handwritten. *Bring a calculator.*
-   You may bring one page of notes on an 8.5” x 11” sheet of paper.
    -   You may use both sides.
    -   You may type your notes.
    -   You may **not** use screenshots of the notes or textbook
    -   You will be turning in the page of notes with the exam, so please add your name to the sheet.

