---
title: "Week 1"
description: "Intro to R & RStudio"
pagetitle: "Week 1 BSTA 511/611"
date: "9/28/2026"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

<!-- ## [Page not yet updated]{style="color:darkorange"} -->

## General info

-   [Syllabus](https://brightspace.ohsu.edu/d2l/common/dialogs/quickLink/quickLink.d2l?ou=16063&type=lti&rcode=A51C7398-E4FD-4C12-844F-190DA44C898D-677&srcou=6606&launchFramed=1&framedName=Syllabus) on Brightspace
-   [Week 1 info](https://brightspace.ohsu.edu/d2l/le/lessons/16063/topics/358889) on Brightspace
    -   Includes link to background survey

## Overview of Week 1

::::: grid
::: g-col-6
### Mon

-   No class. OHSU New Student Orientation
-   [Handout](../resources/BSTA_511_text_R_info_F26_v2.pdf){target="_blank"} with directions on installing R & RStudio and PUBH 523 Lessons to complete for Wednesday

:::

::: g-col-6
### Wed - Day 1

-   Intro to R & RStudio
-   Please have R & RStudio installed for class
-   Complete [Intro to R (PUBH 523) lessons](https://nwakim.github.io/PUBH_523_26F/schedule.html) below before class:
    -   Lesson 1: Welcome
    -   Lesson 3: Download + Intro to R & RStudio
    -   Lesson 4: Basics
    -   Lesson 6: Quarto and .qmd’s

    <!-- -   *If the links for the slides are broken, see the [Summer class website](https://nwakim.github.io/PUBH_523_26Su/schedule.html). Note that the topics are in a different order though.* -->

:::
:::::


## Slides 

| Day | Topic | Slides (F23): html | Slides: pdf | Slides: web-page | Code: qmd |
|--------|--------|--------|--------|--------|--------|
| 1 | Intro to R & RStudio | [Day 1](../slides/Day01_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day01_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day01_bsta511_md.qmd) | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F26/blob/main/slides_md/Day01_bsta511_md.qmd) |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5\]"}

### Practice working in R

-   The PUBH 523 website has interactive R [Practice Tutorials](https://nwakim.github.io/R-practice-tutorials/)
-   If you are new to R, I recommend working through the ones below for some extra practice:
    -   [Warming up: R as a calculator](https://nwakim.github.io/R-practice-tutorials/practice/practice_01.html#warming-up-r-as-a-calculator)
    -   [Relational operators](https://nwakim.github.io/R-practice-tutorials/practice/practice_01.html#relational-operators)
    -   [Putting it together: weekly flu case counts](https://nwakim.github.io/R-practice-tutorials/practice/practice_01.html#putting-it-together-weekly-flu-case-counts)
    

## Homework

-   [HW 1](../homework/HW_1_F26_bsta511.qmd) due on Sat, 10/10
    -   Covers Days 1-3

## Recordings

* There are no pre-recorded lessons for Week 1. Starting Week 2, you will be accessing pre-recorded lessons on the [EchoVideo site for BSTA 511/611](https://echo360.org/section/af47457c-bed2-48d7-84ae-eaa2d44f9add/home). Make sure you can log into this site and view the recordings. 


* __In-class__ recording links are on [Brightspace](https://brightspace.ohsu.edu/d2l/le/lessons/16063/topics/358888). Navigate to _Course Materials_ -> _In-class recordings links_. Note that the password to the recordings is at the top of the page.
